import assert from 'node:assert/strict';
import fs from 'node:fs';
import {defaults,simulate,panelLayout,heatPumpMonthlyWeights} from './model.js';
const profile=JSON.parse(fs.readFileSync(new URL('./data/solar-profile.json',import.meta.url)));
const copy=()=>structuredClone(defaults);
const near=(a,b,tolerance=1e-6)=>assert.ok(Math.abs(a-b)<tolerance,`${a} differs from ${b}`);
assert.equal(profile.values.length,26280);
near(profile.values.reduce((a,b)=>a+b,0)/1000/3,908.34447);
near(heatPumpMonthlyWeights.reduce((a,b)=>a+b,0),1);
let s=copy();
const fit=panelLayout(s.surfaces[0],s);
assert.ok(fit.layoutCount<=fit.theoreticalCount);
assert.ok(fit.layoutCount<=fit.rows*fit.cols);
assert.equal(panelLayout({...s.surfaces[0],widthM:.5,slopeM:36},s).layoutCount,0,'Area alone cannot fit a narrow roof');
assert.equal(panelLayout({...s.surfaces[0],overridePanels:99},s).selectedCount,fit.layoutCount);
assert.equal(panelLayout({...s.surfaces[0],overridePanels:0},s).selectedCount,0);
let r=simulate(s,profile);
near(r.annual.loadKwh,2920);
near(r.annual.standingCost,248.2);
assert.equal(r.monthly.length,12);assert.equal(r.years.length,3);
assert.ok(r.diagnostics.minimumSocKwh>=s.reserveKwh-1e-9);
assert.ok(r.diagnostics.maximumSocKwh<=r.diagnostics.batteryCapacityKwh+1e-9);
assert.ok(r.diagnostics.maximumChargeKwh<=s.batteryPowerKw+1e-9);
assert.ok(r.diagnostics.maximumDischargeKwh<=s.batteryPowerKw+1e-9);
for(const y of r.years){
 near(y.pvKwh,y.directKwh+y.chargeKwh+y.exportKwh+y.curtailKwh);
 near(y.loadKwh,y.directKwh+y.batteryKwh+y.importKwh-y.gridChargeKwh);
 assert.ok(y.coveragePct>=0&&y.coveragePct<=100);
}
const totals=r.years.reduce((v,y)=>v+y.pvKwh+y.importKwh-y.loadKwh-y.exportKwh-y.curtailKwh-y.lossKwh,0);
near(totals,r.diagnostics.finalSocKwh-r.diagnostics.initialSocKwh);
assert.ok(r.annual.gridChargeKwh>0);
s=copy();s.gridCharge=false;
r=simulate(s,profile);near(r.annual.gridChargeKwh,0);
assert.ok(r.annual.batterySolarKwh<=r.annual.batteryKwh+1e-6);
s=copy();s.surfaces.forEach(x=>x.enabled=false);s.batteryKwh=0;
r=simulate(s,profile);near(r.annual.pvKwh,0);near(r.annual.importKwh,2920);near(r.annual.saving,0);
s.ashpEnabled=true;s.ashpAnnualKwh=3000;
r=simulate(s,profile);near(r.annual.loadKwh,5920);near(r.annual.ashpKwh,3000);
assert.ok(r.monthly[0].ashpKwh>r.monthly[6].ashpKwh);
s=copy();s.exportLimitKw=0;r=simulate(s,profile);near(r.annual.exportKwh,0);assert.ok(r.annual.curtailKwh>0);
s=copy();s.inverterKw=0;r=simulate(s,profile);near(r.annual.directKwh,0);near(r.annual.chargeKwh,0);near(r.annual.batteryKwh,0);near(r.annual.saving,0);
console.log('PASS: 26,280 source hours, panel fit, overrides, demand, ASHP, tariff standing charge, storage bounds, hourly-flow annual balances, no-PV baseline, grid-charge toggle, export and inverter limits.');
console.log(JSON.stringify(simulate(copy(),profile).annual,null,2));
